version: "3"
services:
  # no database in moment - mysql:
  nodejs:
    build: ./nodejs
    command: npm start
    ports:
    - "3001:3001"
    volumes:
    - .:/usr/app
  python:
    build: ./python
    command: python index.py
    ports:
    - "5000:5000"
    volumes:
    - .:/app